site_name: "Portfolio — Victor Ouledi"
site_url: "https://victorouledi.github.io/Portfolio_data_analyst_et_data_scientist_Victor_OULEDI/"
repo_url: "https://github.com/Victorouledi/Portfolio_data_analyst_et_data_scientist_Victor_OULEDI"
repo_name: "Repo GitHub"
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - content.code.copy
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-6
        name: Mode sombre
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mode clair

plugins:
  - search
  - mkdocs-jupyter    # utile si tu publies des notebooks .ipynb

markdown_extensions:
  - attr_list
  - md_in_html               # <div class="grid cards" markdown> rend bien les cartes
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji:          # nouvelle API (ne pas utiliser materialx.*)
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Accueil: index.md
  - Projets:
      - Aperçu: projets/index.md
      - IA & NLP — Classification de plaintes: projets/nlp-lstm.md
      - Computer Vision — Imagerie médicale: projets/imagerie-medicale.md
      - Clustering & ACP — Criminalité aux États-Unis: projets/crime-usa.md
      - AFC — Élections 2022 (IDF): projets/elections-afc.md
      - Data Analysis in R — Prix hédoniques (Lyon): projets/prix-hedoniques-lyon.md
      - Data Analysis in R — Salaires (panel US): projets/salaires-panel-us.md
      - Data Analysis in Python — Terre de Liens: projets/terre-de-liens.md
      - Certifications: projets/certifications.md
  - À propos: apropos.md
  - Contact: contacts.md

